services:
  api01:
    hostname: api01
    build: .
    environment:
      - DATABASE_URL=ecto://postgres:postgres@postgres/url_shortener_dev
      - SECRET_KEY_BASE=WxMbiamDW+larjkiC3tRgWhaNsgpUSYI9IwPnx1OLZIif474mkR2aPk8ALbtvFSL
      - PHX_SERVER=true
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128MB"
    networks:
      - url-shortener

  nginx: 
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - "9999:9999"
    deploy:
      resources: 
        limits:
          cpus:  "0.1"
          memory: "16MB"
    networks: 
      - url-shortener

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256MB"
    networks:
      - url-shortener

  redis:
    image: redis/redis-stack:latest
    command: 'redis-server --appendonly no --save "" --protected-mode no'
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "64MB"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - url-shortener

volumes:
  postgres-data:

networks:
  url-shortener:
    driver: bridge
